version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
      keycloak:
        condition: service_started  # Wait for Keycloak to start
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ping_db
      - SPRING_DATASOURCE_USERNAME=ping_user
      - SPRING_DATASOURCE_PASSWORD=ping_password
    command: ["sh", "-c", "sleep 10 && java -jar app.jar"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_URL=http://localhost:8180

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ping_user
      POSTGRES_PASSWORD: ping_password
      POSTGRES_DB: postgres  # Default DB for initialization
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d  # Mount init script
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ping_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak_db
      - KC_DB_USERNAME=ping_user
      - KC_DB_PASSWORD=ping_password
      - KC_HOSTNAME=localhost
      - KC_HTTP_PORT=8180
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - "8180:8180"
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    volumes:
      - ./keycloak/ping-realm.json:/opt/keycloak/data/import/ping-realm.json
    command: ["start-dev", "--import-realm"]

volumes:
  pgdata: