# templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ping-app.name" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ping-app.labels" . | nindent 4 }}
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ping-app.labels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      labels:
        {{- include "ping-app.labels" . | nindent 8 }}
        app: frontend
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox
        command: ["sh", "-c", "until nc -z backend {{ .Values.backend.port }}; do echo waiting for backend; sleep 2; done;"]
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: REACT_APP_BACKEND_URL
          value: {{ .Values.frontend.env.backendUrl }}
        - name: REACT_APP_KEYCLOAK_URL
          value: {{ .Values.frontend.env.keycloakUrl }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ping-app.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
  selector:
    {{- include "ping-app.labels" . | nindent 4 }}
    app: frontend
