apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.frontendPath }}
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.port }}
          - path: {{ .Values.ingress.keycloakPath }}
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.keycloak.port }} 